#pragma config(Motor,  port1,           backRight,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           midRight1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           midRIght2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           midLeft1,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           midLeft2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           frontLeft,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#define yAxis vexRT[Ch3]
#define xAxis vexRT[Ch1]
#define rAxis vexRT[Ch1]
//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

void arcadeDrive(int xValue, int yValue, int rValue){
	motor[frontLeft] = +xValue + yValue - rValue;
	motor[midLeft2] = +xValue + yValue - rValue;
	motor[midLeft1] = +xValue + yValue - rValue;
	motor[backLeft] = +xValue + yValue - rValue;
	motor[frontRight] = +xValue + yValue - rValue;
	motor[midRIght2] = +xValue + yValue - rValue;
	motor[midRight1] = +xValue + yValue - rValue;
	motor[backRight] = +xValue + yValue - rValue;
}

void pre_auton()
{
  bStopTasksBetweenModes = true;
}

task autonomous()
{
  arcadeDrive(127,127,0);
  wait1Msec(2000);
}

task usercontrol(){
	while (true) {
		arcadeDrive(xAxis,yAxis,rAxis);
	}
}
